In [1]:
import pandas as pd
import numpy as np
import os
import glob

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)
print("Environment is ready!")

Pandas version: 2.3.3
NumPy version: 2.2.6
Environment is ready!

In [2]:
cic_path = "../data/CICIDS2017/raw"

cic_files = glob.glob(os.path.join(cic_path, "*.csv"))

print("Number of CICIDS2017 CSV files:", len(cic_files))

for file in cic_files:
    print(os.path.basename(file))

Number of CICIDS2017 CSV files: 8
Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
Friday-WorkingHours-Morning.pcap_ISCX.csv
Monday-WorkingHours.pcap_ISCX.csv
Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
Tuesday-WorkingHours.pcap_ISCX.csv
Wednesday-workingHours.pcap_ISCX.csv

In [3]:
monday_file = os.path.join(
    cic_path,
    "Monday-WorkingHours.pcap_ISCX.csv"
)

df_monday = pd.read_csv(monday_file)

print("Dataset shape:", df_monday.shape)
print("\nColumn names:")
print(df_monday.columns.tolist())

Dataset shape: (529918, 79)

Column names:
[' Destination Port', ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets', 'Total Length of Fwd Packets', ' Total Length of Bwd Packets', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Fwd Packet Length Mean', ' Fwd Packet Length Std', 'Bwd Packet Length Max', ' Bwd Packet Length Min', ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size', ' Avg Fwd Segment Size', ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward', ' Init_Win_bytes_backward', ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min', ' Label']

In [4]:
print("First 5 rows:")
display(df_monday.head())

print("\nData types:")
display(df_monday.dtypes)

print("\nMissing values:")
display(df_monday.isnull().sum().sort_values(ascending=False).head(15))

print("\nDuplicate rows:", df_monday.duplicated().sum())

print("\nLabel distribution:")
display(df_monday[" Label"].value_counts())

First 5 rows:

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,49188,4,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,49486,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

Data types:

 Destination Port                int64
 Flow Duration                   int64
 Total Fwd Packets               int64
 Total Backward Packets          int64
Total Length of Fwd Packets      int64
                                ...
Idle Mean                      float64
 Idle Std                      float64
 Idle Max                        int64
 Idle Min                        int64
 Label                          object
Length: 79, dtype: object

Missing values:

Flow Bytes/s                    64
 Flow Duration                   0
 Destination Port                0
 Total Backward Packets          0
Total Length of Fwd Packets      0
 Total Length of Bwd Packets     0
 Total Fwd Packets               0
 Fwd Packet Length Max           0
 Fwd Packet Length Min           0
 Fwd Packet Length Std           0
 Fwd Packet Length Mean          0
Bwd Packet Length Max            0
 Bwd Packet Length Min           0
 Bwd Packet Length Mean          0
 Bwd Packet Length Std           0
dtype: int64

Duplicate rows: 26935

Label distribution:

 Label
BENIGN    529918
Name: count, dtype: int64

In [5]:
for file in cic_files:
    print("\n" + "=" * 70)
    print(os.path.basename(file))

    labels = pd.read_csv(file, usecols=[" Label"])[" Label"]

    print("Rows:", len(labels))
    print("Labels:")
    print(labels.value_counts())

======================================================================
Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Rows: 225745
Labels:
 Label
DDoS      128027
BENIGN     97718
Name: count, dtype: int64

======================================================================
Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
Rows: 286467
Labels:
 Label
PortScan    158930
BENIGN      127537
Name: count, dtype: int64

======================================================================
Friday-WorkingHours-Morning.pcap_ISCX.csv
Rows: 191033
Labels:
 Label
BENIGN    189067
Bot         1966
Name: count, dtype: int64

======================================================================
Monday-WorkingHours.pcap_ISCX.csv
Rows: 529918
Labels:
 Label
BENIGN    529918
Name: count, dtype: int64

======================================================================
Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
Rows: 288602
Labels:
 Label
BENIGN          288566
Infiltration        36
Name: count, dtype: int64

======================================================================
Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
Rows: 170366
Labels:
 Label
BENIGN                        168186
Web Attack � Brute Force        1507
Web Attack � XSS                 652
Web Attack � Sql Injection        21
Name: count, dtype: int64

======================================================================
Tuesday-WorkingHours.pcap_ISCX.csv
Rows: 445909
Labels:
 Label
BENIGN         432074
FTP-Patator      7938
SSH-Patator      5897
Name: count, dtype: int64

======================================================================
Wednesday-workingHours.pcap_ISCX.csv
Rows: 692703
Labels:
 Label
BENIGN              440031
DoS Hulk            231073
DoS GoldenEye        10293
DoS slowloris         5796
DoS Slowhttptest      5499
Heartbleed              11
Name: count, dtype: int64

In [6]:
label_summary = []

for file in cic_files:
    labels = pd.read_csv(file, usecols=[" Label"])[" Label"]
    
    counts = labels.value_counts()
    
    for label, count in counts.items():
        label_summary.append({
            "File": os.path.basename(file),
            "Label": label.strip(),
            "Count": count
        })

label_df = pd.DataFrame(label_summary)

display(label_df)

,File,Label,Count
0,Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv,DDoS,128027
1,Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv,BENIGN,97718
2,Friday-WorkingHours-Afternoon-PortScan.pcap_IS...,PortScan,158930
3,Friday-WorkingHours-Afternoon-PortScan.pcap_IS...,BENIGN,127537
4,Friday-WorkingHours-Morning.pcap_ISCX.csv,BENIGN,189067
5,Friday-WorkingHours-Morning.pcap_ISCX.csv,Bot,1966
6,Monday-WorkingHours.pcap_ISCX.csv,BENIGN,529918
7,Thursday-WorkingHours-Afternoon-Infilteration....,BENIGN,288566
8,Thursday-WorkingHours-Afternoon-Infilteration....,Infiltration,36
9,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,BENIGN,168186
10,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,Web Attack � Brute Force,1507
11,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,Web Attack � XSS,652
12,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,Web Attack � Sql Injection,21
13,Tuesday-WorkingHours.pcap_ISCX.csv,BENIGN,432074
14,Tuesday-WorkingHours.pcap_ISCX.csv,FTP-Patator,7938
15,Tuesday-WorkingHours.pcap_ISCX.csv,SSH-Patator,5897
16,Wednesday-workingHours.pcap_ISCX.csv,BENIGN,440031
17,Wednesday-workingHours.pcap_ISCX.csv,DoS Hulk,231073
18,Wednesday-workingHours.pcap_ISCX.csv,DoS GoldenEye,10293
19,Wednesday-workingHours.pcap_ISCX.csv,DoS slowloris,5796
20,Wednesday-workingHours.pcap_ISCX.csv,DoS Slowhttptest,5499
21,Wednesday-workingHours.pcap_ISCX.csv,Heartbleed,11

In [7]:
overall_labels = label_df.groupby("Label")["Count"].sum().sort_values(ascending=False)

print("Overall CICIDS2017 Label Distribution:")
display(overall_labels.to_frame())

Overall CICIDS2017 Label Distribution:

                              Count
Label
BENIGN                      2273097
DoS Hulk                     231073
PortScan                     158930
DDoS                         128027
DoS GoldenEye                 10293
FTP-Patator                    7938
SSH-Patator                    5897
DoS slowloris                  5796
DoS Slowhttptest               5499
Bot                            1966
Web Attack � Brute Force       1507
Web Attack � XSS                652
Infiltration                     36
Web Attack � Sql Injection       21
Heartbleed                       11