In [1]:
import pandas as pd
import numpy as np
import os

print("UNSW-NB15 preprocessing environment ready!")

UNSW-NB15 preprocessing environment ready!

In [2]:
train_path = "../data/UNSW-NB15/raw/UNSW_NB15_training-set.csv"
test_path = "../data/UNSW-NB15/raw/UNSW_NB15_testing-set.csv"

print("Training file:", train_path)
print("Testing file:", test_path)

Training file: ../data/UNSW-NB15/raw/UNSW_NB15_training-set.csv
Testing file: ../data/UNSW-NB15/raw/UNSW_NB15_testing-set.csv

In [3]:
train_df = pd.read_csv(train_path)

print("Training dataset loaded successfully!")
print("Training shape:", train_df.shape)

Training dataset loaded successfully!
Training shape: (175341, 45)

In [4]:
test_df = pd.read_csv(test_path)

print("Testing dataset loaded successfully!")
print("Testing shape:", test_df.shape)

Testing dataset loaded successfully!
Testing shape: (82332, 45)

In [5]:
print("Training columns:")
print(train_df.columns.tolist())

print("\nNumber of columns:", len(train_df.columns))

Training columns:
['id', 'dur', 'proto', 'service', 'state', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sttl', 'dttl', 'sload', 'dload', 'sloss', 'dloss', 'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin', 'tcprtt', 'synack', 'ackdat', 'smean', 'dmean', 'trans_depth', 'response_body_len', 'ct_srv_src', 'ct_state_ttl', 'ct_dst_ltm', 'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm', 'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'ct_src_ltm', 'ct_srv_dst', 'is_sm_ips_ports', 'attack_cat', 'label']

Number of columns: 45

In [6]:
print("Training dataset sample:")
display(train_df.head())

print("\nTesting dataset sample:")
display(test_df.head())

Training dataset sample:

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.121478,tcp,-,FIN,6,4,258,172,74.087490,...,1,1,0,0,0,1,1,0,Normal,0
1,2,0.649902,tcp,-,FIN,14,38,734,42014,78.473372,...,1,2,0,0,0,1,6,0,Normal,0
2,3,1.623129,tcp,-,FIN,8,16,364,13186,14.170161,...,1,3,0,0,0,2,6,0,Normal,0
3,4,1.681642,tcp,ftp,FIN,12,12,628,770,13.677108,...,1,3,1,1,0,2,1,0,Normal,0
4,5,0.449454,tcp,-,FIN,10,6,534,268,33.373826,...,1,40,0,0,0,2,39,0,Normal,0

Testing dataset sample:

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.000011,udp,-,INT,2,0,496,0,90909.0902,...,1,2,0,0,0,1,2,0,Normal,0
1,2,0.000008,udp,-,INT,2,0,1762,0,125000.0003,...,1,2,0,0,0,1,2,0,Normal,0
2,3,0.000005,udp,-,INT,2,0,1068,0,200000.0051,...,1,3,0,0,0,1,3,0,Normal,0
3,4,0.000006,udp,-,INT,2,0,900,0,166666.6608,...,1,3,0,0,0,2,3,0,Normal,0
4,5,0.000010,udp,-,INT,2,0,2126,0,100000.0025,...,1,3,0,0,0,2,3,0,Normal,0

In [7]:
print("Target-related columns:")

for column in train_df.columns:
    if column in ["label", "attack_cat"]:
        print(column)

print("\nLabel distribution:")
print(train_df["label"].value_counts())

print("\nAttack category distribution:")
print(train_df["attack_cat"].value_counts(dropna=False))

Target-related columns:
attack_cat
label

Label distribution:
label
1    119341
0     56000
Name: count, dtype: int64

Attack category distribution:
attack_cat
Normal            56000
Generic           40000
Exploits          33393
Fuzzers           18184
DoS               12264
Reconnaissance    10491
Analysis           2000
Backdoor           1746
Shellcode          1133
Worms               130
Name: count, dtype: int64

In [8]:
missing_train = train_df.isnull().sum()
missing_test = test_df.isnull().sum()

print("Training missing values:")
print(missing_train[missing_train > 0])

print("\nTesting missing values:")
print(missing_test[missing_test > 0])

Training missing values:
Series([], dtype: int64)

Testing missing values:
Series([], dtype: int64)

In [9]:
train_df.columns = train_df.columns.str.strip()
test_df.columns = test_df.columns.str.strip()

print("Column names cleaned successfully!")

Column names cleaned successfully!

In [10]:
train_df["attack_cat"] = train_df["attack_cat"].fillna("Normal")
test_df["attack_cat"] = test_df["attack_cat"].fillna("Normal")

train_df["attack_cat"] = train_df["attack_cat"].astype(str).str.strip()
test_df["attack_cat"] = test_df["attack_cat"].astype(str).str.strip()

print("Attack categories cleaned successfully!")

print("\nTraining attack categories:")
print(train_df["attack_cat"].value_counts())

Attack categories cleaned successfully!

Training attack categories:
attack_cat
Normal            56000
Generic           40000
Exploits          33393
Fuzzers           18184
DoS               12264
Reconnaissance    10491
Analysis           2000
Backdoor           1746
Shellcode          1133
Worms               130
Name: count, dtype: int64

In [11]:
train_df = train_df.drop(columns=["id"], errors="ignore")
test_df = test_df.drop(columns=["id"], errors="ignore")

print("Identifier column removed.")
print("Training shape:", train_df.shape)
print("Testing shape:", test_df.shape)

Identifier column removed.
Training shape: (175341, 44)
Testing shape: (82332, 44)

In [12]:
print("Categorical columns:")

categorical_columns = train_df.select_dtypes(
    include=["object"]
).columns.tolist()

print(categorical_columns)

print("\nNumeric columns:")
print(len(train_df.select_dtypes(include=[np.number]).columns))

Categorical columns:
['proto', 'service', 'state', 'attack_cat']

Numeric columns:
40

In [13]:
categorical_features = [
    "proto",
    "service",
    "state"
]

existing_categorical = [
    column for column in categorical_features
    if column in train_df.columns
]

print("Categorical features to encode:")
print(existing_categorical)

train_encoded = pd.get_dummies(
    train_df,
    columns=existing_categorical,
    dtype=int
)

test_encoded = pd.get_dummies(
    test_df,
    columns=existing_categorical,
    dtype=int
)

print("\nEncoding completed!")
print("Training shape:", train_encoded.shape)
print("Testing shape:", test_encoded.shape)

Categorical features to encode:
['proto', 'service', 'state']

Encoding completed!
Training shape: (175341, 196)
Testing shape: (82332, 192)

In [14]:
target_columns = ["label", "attack_cat"]

feature_columns = [
    column for column in train_encoded.columns
    if column not in target_columns
]

train_features = train_encoded[feature_columns].copy()
test_features = test_encoded.drop(
    columns=target_columns,
    errors="ignore"
).copy()

train_features, test_features = train_features.align(
    test_features,
    join="left",
    axis=1,
    fill_value=0
)

print("Training feature shape:", train_features.shape)
print("Testing feature shape:", test_features.shape)

Training feature shape: (175341, 194)
Testing feature shape: (82332, 194)

In [15]:
train_features = train_features.replace(
    [np.inf, -np.inf],
    np.nan
)

test_features = test_features.replace(
    [np.inf, -np.inf],
    np.nan
)

train_features = train_features.fillna(0)
test_features = test_features.fillna(0)

print("Missing and infinite values handled.")

print("Training missing values:", train_features.isnull().sum().sum())
print("Testing missing values:", test_features.isnull().sum().sum())

Missing and infinite values handled.
Training missing values: 0
Testing missing values: 0

In [16]:
y_train = train_encoded["label"].astype(int)
y_test = test_encoded["label"].astype(int)

print("Binary labels prepared!")

print("\nTraining labels:")
print(y_train.value_counts())

print("\nTesting labels:")
print(y_test.value_counts())

print("\nLabel meaning:")
print("0 = NORMAL")
print("1 = ATTACK")

Binary labels prepared!

Training labels:
label
1    119341
0     56000
Name: count, dtype: int64

Testing labels:
label
1    45332
0    37000
Name: count, dtype: int64

Label meaning:
0 = NORMAL
1 = ATTACK

In [17]:
train_ml_ready = train_features.copy()
train_ml_ready["Binary_Label"] = y_train.values

test_ml_ready = test_features.copy()
test_ml_ready["Binary_Label"] = y_test.values

print("ML-ready training dataset:", train_ml_ready.shape)
print("ML-ready testing dataset:", test_ml_ready.shape)

ML-ready training dataset: (175341, 195)
ML-ready testing dataset: (82332, 195)

In [18]:
output_dir = "../data/UNSW-NB15/ml_ready"

os.makedirs(output_dir, exist_ok=True)

train_output = os.path.join(
    output_dir,
    "UNSW_NB15_training_ml_ready.csv"
)

test_output = os.path.join(
    output_dir,
    "UNSW_NB15_testing_ml_ready.csv"
)

train_ml_ready.to_csv(
    train_output,
    index=False
)

test_ml_ready.to_csv(
    test_output,
    index=False
)

print("UNSW-NB15 preprocessing completed successfully!")

print("\nTraining saved to:")
print(train_output)

print("\nTesting saved to:")
print(test_output)

UNSW-NB15 preprocessing completed successfully!

Training saved to:
../data/UNSW-NB15/ml_ready\UNSW_NB15_training_ml_ready.csv

Testing saved to:
../data/UNSW-NB15/ml_ready\UNSW_NB15_testing_ml_ready.csv